### ISSUE TITLE
phone_verify

### ISSUE THREAD

**Issue by chemhong** [pangliang/futu-opend-docker#1]
命令提示:input_phone_verify_code -code=123456

請問 dokcer 已在進行中如何 打verify_code？ 謝謝

**Comment by pangliang** [comment]
在台式机客户端验证一下，之后应该就不需要验证了



---Original---

**Comment by chemhong** [comment]
> 在台式机客户端验证一下，之后应该就不需要验证了
> […](#)
> ---Original--- From: "chemhong"<notifications@github.com&gt; Date: Wed, Oct 2, 2019 00:28 AM To: "pangliang/futu-opend-docker"<futu-opend-docker@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [pangliang/futu-opend-docker] phone_verify (#1) 命令提示:input_phone_verify_code -code=123456 請問 dokcer 已在進行中如何 打verify_code？ 謝謝 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

謝謝～～～

**Comment by chemhong** [comment]
台式机客户端验证完 拿去docker 上用 還是要再验证，你有試過嗎？謝謝
